%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: C:\Users\Marta Niccolini\Documents\Courses\Coursera_DataAnalyst\Data Science Project\2015 Bank Holidays.csv
%
% Auto-generated by MATLAB on 23-Aug-2022 11:25:28

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 2, "Encoding", "UTF-8");

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Date", "Holiday"];
opts.VariableTypes = ["datetime", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "Holiday", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "Holiday", "EmptyFieldRule", "auto");
opts = setvaropts(opts, "Date", "InputFormat", "MM/dd/yy");

% Import the data
BankHolidays = readtable("C:\Users\Marta Niccolini\Documents\Courses\Coursera_DataAnalyst\Data Science Project\2015 Bank Holidays.csv", opts);

BankHolidays.Date.Format = "yyyy-MM-dd";

%% Clear temporary variables
clear opts